### ISSUE TITLE
if libcal fails to return current users, will it return the software?

### ISSUE THREAD

**Issue by kenirwin** [Miamiohlibs/SoftwareCheckout2#15]
Scenario:
- 5 people have something checked out thru Adobe
- LibCal is offline or returns a non-200 response
- Adobe returns a list of 5 current users
- Would the system then compare 0 libcal users to 5 adobe users and issue a revocation for those five users?

**Comment by kenirwin** [comment]
I simulated a failed request by inserting a typo into the URL (gets a 404 of course). I believe that what's happening here is it proceeds to attempt to process, filter, etc the request on the null object returned by the api handler. What do we need to do to catch this and kill the adobe service instead of generating an unhandled exception?

```
(node:50844) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:50844) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at axiosLogPrep (/Users/irwinkr/Documents/GitHub/SoftwareCheckout2/helpers/utils.js:20:3)
    at LibCalApi.getBookings (/Users/irwinkr/Documents/GitHub/SoftwareCheckout2/models/LibCalApi.js:43:57)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/irwinkr/Documents/GitHub/SoftwareCheckout2/temp.js:28:13
(node:50844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:50844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```
