### ISSUE TITLE
adobeRepo.getGroupMembers(groupName) fails when there's a forward slash in the groupName

### ISSUE THREAD

**Issue by kenirwin** [Miamiohlibs/SoftwareCheckout2#57]
When the Adobe console user group name contains a forward slash (e.g. "Faculty/Staff CC") the `adobeRepo.getGroupMembers(groupName)` fails:

```
TypeError: Cannot read properties of undefined (reading 'users')
    at AdobeUserMgmtService.getPaginatedResults (/Users/irwinkr/Documents/GitHub/SoftwareCheckout2/repositories/AdobeRepository.js:38:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AdobeUserMgmtService.getGroupMembers (/Users/irwinkr/Documents/GitHub/SoftwareCheckout2/repositories/AdobeRepository.js:61:15)
```

Can we fix this by escaping the query somehow, or is this something we just have to note in the docuementation?

**Comment by kenirwin** [comment]
What it might make sense to do is: add an optional config field for the groupId. If groupId is present, use it; if not, use the group name; throw some kind of warning if group name contains a slash
